# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build_and_test: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: 
          command: npm install typescript
      - run:  
          command: npm install ts-node
          name: Install other dependencies
      - run:
          command: npm run test
          name: Test application
      - persist_to_workspace:
          root: ~/app
          paths:
            - .

workflows:
  build_and_test_app:
    jobs:
      - build_and_test
